name = "portfolio-hono"
main = "src/index.tsx"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[env.production]
name = "portfolio-hono"

[env.development]
name = "portfolio-hono-dev"
