name = "portfolio-hono"
main = "dist/_worker.js"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat"]

[build]
command = "vite build"

[vars]
NODE_ENV = "production"

[env.production]
name = "portfolio-hono"

[env.development]
name = "portfolio-hono-dev"
