name = "portfolio-hono"
main = "dist/portfolio_hono/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./dist/client"

[vars]
NODE_ENV = "production"

[env.production]
name = "portfolio-hono"

[env.development]
name = "portfolio-hono-dev"
